name: Preprocessing Workflow

on:
  push:   
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo + LFS
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Jalankan preprocessing otomatis
      - name: Run preprocessing
        run: |
          python preprocessing/automate_Bustanul-Khair.py

      # Upload hasil preprocessing sebagai artifact
      - name: Upload processed dataset
        uses: actions/upload-artifact@v4
        with:
          name: processed-dataset
          path: preprocessing/
